// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9buhYYKojdF7aOBwGPG7jmy9bG6ejmTQ',
    appId: '1:1009556560307:android:1a99b2873e18fedb4153c6',
    messagingSenderId: '1009556560307',
    projectId: 'muslim-pocket-ca0b0',
    databaseURL: 'https://muslim-pocket-ca0b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'muslim-pocket-ca0b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb7VkyHDCXXTXkzz1sTprSBgYGeyrWedM',
    appId: '1:1009556560307:ios:c002b699b9feee2c4153c6',
    messagingSenderId: '1009556560307',
    projectId: 'muslim-pocket-ca0b0',
    databaseURL: 'https://muslim-pocket-ca0b0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'muslim-pocket-ca0b0.firebasestorage.app',
    iosBundleId: 'com.muslim.pocket',
  );

}