// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwtCgPyMmai6OZPv5-ZXK3LjRjnifQLWM',
    appId: '1:351761392227:android:2366adea08aedc86f1ce56',
    messagingSenderId: '351761392227',
    projectId: 'muslim-pocket-6f5a1',
    databaseURL: 'https://muslim-pocket-6f5a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'muslim-pocket-6f5a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrv7Yax2nxomqFC6G-44qZFNR29srPEvw',
    appId: '1:351761392227:ios:154a647bfe61f089f1ce56',
    messagingSenderId: '351761392227',
    projectId: 'muslim-pocket-6f5a1',
    databaseURL: 'https://muslim-pocket-6f5a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'muslim-pocket-6f5a1.appspot.com',
    iosBundleId: 'com.muslim.pocket',
  );
}
